[package]
authors = ["Sam Scott <sam@osohq.com>"]
edition = "2018"
categories = ["encoding", "web-programming"]
description = "Querystrings for Serde"
documentation = "https://docs.rs/serde_qs"
keywords = ["serde", "serialization", "querystring"]
license = "MIT/Apache-2.0"
name = "serde_qs"
repository = "https://github.com/samscott89/serde_qs"
readme = "README.md"
version = "0.8.4"

[dependencies]
actix-web = { version = "3.3", optional = true, package = "actix-web", default-features = false }
actix-web2 = { package = "actix-web", version = "2.0", optional = true, default-features = false }
futures = { version = "0.3", optional = true }
percent-encoding = "2.1"
serde = "1.0"
thiserror = "1.0"
tracing = { version = "0.1", optional = true }
warp-framework = { package = "warp", version = "0.3", default-features = false, optional = true }

[dev-dependencies]
csv = "1.1"
rand = "0.8"
serde_derive = "1.0"
serde_urlencoded = "0.7"

[features]
default = []
actix = ["actix-web", "futures"]
actix2 = ["actix-web2", "futures"]
warp = ["futures", "tracing", "warp-framework"]

[package.metadata.docs.rs]
features = ["actix", "warp"]
